export const festivalStats = [
  { label: "Upcoming events", value: "8", detail: "Live lineup from the official site" },
  { label: "Highlights", value: "14", detail: "Real site photo assets" },
  { label: "Testimonials", value: "2", detail: "Short guest quotes" },
  { label: "Platform pages", value: "6", detail: "Events, shop, gallery, news, verify" },
];

export const featuredTimeline = [
  {
    time: "16:00",
    title: "Doors Open",
    description: "Check-in, wristbands, and first arrivals at Lemo Green Park.",
  },
  {
    time: "18:00",
    title: "Opening Set",
    description: "A clean opening with the first headline performers on stage.",
  },
  {
    time: "19:30",
    title: "Featured Acts",
    description: "The main performances, guest moments, and crowd energy peak.",
  },
  {
    time: "22:00",
    title: "Late Night Energy",
    description: "DJ sets, crowd moments, and a strong finish after dark.",
  },
  {
    time: "00:00",
    title: "Finale",
    description: "A midnight send-off with the full crowd on its feet.",
  },
];

export const ticketTiers = [
  {
    name: "General Access",
    priceCents: 6500,
    benefits: ["Access to the main event", "QR ticket delivery", "Live support"],
    spotlight: true,
  },
  {
    name: "VIP Access",
    priceCents: 9900,
    benefits: ["Priority entry", "VIP lane support", "Premium event view"],
    spotlight: false,
  },
  {
    name: "Group Pass",
    priceCents: 24500,
    benefits: ["Bundle savings", "Shared checkout", "Fast ticket distribution"],
    spotlight: false,
  },
];

export const demoEvents = [
  {
    slug: "lemo-fest-yanos-hip-hop",
    title: "Lemo Fest Yanos Hip-Hop",
    description:
      "A high-energy opening night with amapiano, hip-hop, and crowd-heavy moments at Lemo Green Park.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-04-25T11:00:00.000Z",
    endsAt: "2026-04-25T22:00:00.000Z",
    ticketPriceCents: 6500,
    currency: "ZAR",
    capacity: 2500,
    featured: true,
    published: true,
    imageUrl: "/lemofest/upcoming-event-1.png",
    galleryUrls: ["/lemofest/upcoming-event-1.png", "/lemofest/blog1.jpg"],
    tags: ["amapiano", "hip-hop", "featured"],
    schedule: featuredTimeline,
    displayDateLabel: "25 APRIL 2026",
  },
  {
    slug: "lemo-fest-gospel-experience",
    title: "Lemo Fest Gospel Experience",
    description:
      "A community gospel gathering with uplifting performances, strong vocals, and a family-friendly crowd.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-05-30T09:00:00.000Z",
    endsAt: "2026-05-30T18:30:00.000Z",
    ticketPriceCents: 5000,
    currency: "ZAR",
    capacity: 2200,
    featured: true,
    published: true,
    imageUrl: "/lemofest/upcoming-event-2.png",
    galleryUrls: ["/lemofest/upcoming-event-2.png", "/lemofest/blog2.jpg"],
    tags: ["gospel", "community", "family"],
    schedule: featuredTimeline,
    displayDateLabel: "30 MAY 2026",
  },
  {
    slug: "lemo-fest-lovers-and-friends",
    title: "Lemo Fest Lovers & Friends",
    description:
      "A relaxed night for couples and groups of friends, built around live music and easy social energy.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-06-27T17:00:00.000Z",
    endsAt: "2026-06-27T23:00:00.000Z",
    ticketPriceCents: 5500,
    currency: "ZAR",
    capacity: 1800,
    featured: false,
    published: true,
    imageUrl: "/lemofest/upcoming-event-3.png",
    galleryUrls: ["/lemofest/upcoming-event-3.png", "/lemofest/blog3.jpg"],
    tags: ["couples", "music", "social"],
    schedule: featuredTimeline,
    displayDateLabel: "27 JUNE 2026",
  },
  {
    slug: "lemo-fest-golf-open",
    title: "Lemo Fest Golf Open",
    description:
      "A premium day of golf, hospitality, and brand networking with the Lemo Fest atmosphere.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-07-25T08:00:00.000Z",
    endsAt: "2026-07-25T18:00:00.000Z",
    ticketPriceCents: 9800,
    currency: "ZAR",
    capacity: 2200,
    featured: false,
    published: true,
    imageUrl: "/lemofest/upcoming-event-4.png",
    galleryUrls: ["/lemofest/upcoming-event-4.png", "/lemofest/blog5.jpg"],
    tags: ["golf", "corporate", "networking"],
    schedule: featuredTimeline,
    displayDateLabel: "25 JULY 2026",
  },
  {
    slug: "lemo-fest-afro-soul-and-jazz",
    title: "Lemo Fest Afro Soul & Jazz",
    description:
      "Smooth live instruments, soulful vocals, and a relaxed after-dark set for the grown-up crowd.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-08-29T18:00:00.000Z",
    endsAt: "2026-08-29T23:30:00.000Z",
    ticketPriceCents: 6200,
    currency: "ZAR",
    capacity: 1700,
    featured: false,
    published: true,
    imageUrl: "/lemofest/upcoming-event-5.png",
    galleryUrls: ["/lemofest/upcoming-event-5.png", "/lemofest/blog6.jpg"],
    tags: ["afro", "jazz", "soul"],
    schedule: featuredTimeline,
    displayDateLabel: "29 AUGUST 2026",
  },
  {
    slug: "lemo-fest-spin-explosion",
    title: "Lemo Fest Spin Explosion",
    description:
      "A loud dance-floor finale with DJs, movement, and a late-night finish that sells out fast.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-09-26T18:00:00.000Z",
    endsAt: "2026-09-27T01:00:00.000Z",
    ticketPriceCents: 7500,
    currency: "ZAR",
    capacity: 2200,
    featured: false,
    published: true,
    imageUrl: "/lemofest/upcoming-event-6.png",
    galleryUrls: ["/lemofest/upcoming-event-6.png", "/lemofest/blog7.jpg"],
    tags: ["dj", "dance", "night"],
    schedule: featuredTimeline,
    displayDateLabel: "26 SEPTEMBER 2026",
  },
  {
    slug: "lemo-fest-fashion-art-and-comedy",
    title: "Lemo Fest Fashion, Art & Comedy",
    description:
      "A style and culture showcase that mixes fashion, artwork, and live comedy into one easy night out.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-11-14T11:00:00.000Z",
    endsAt: "2026-11-14T20:00:00.000Z",
    ticketPriceCents: 4500,
    currency: "ZAR",
    capacity: 1800,
    featured: false,
    published: true,
    imageUrl: "/lemofest/upcoming-event-7.png",
    galleryUrls: ["/lemofest/upcoming-event-7.png", "/lemofest/blog8.jpg"],
    tags: ["fashion", "art", "comedy"],
    schedule: featuredTimeline,
    displayDateLabel: "14 NOVEMBER 2026",
  },
  {
    slug: "lemo-fest-hangout",
    title: "Lemo Fest Hangout",
    description:
      "A laid-back open event for friends, food stalls, music, and easy festival socialising.",
    location: "Lemo Green Park",
    venue: "Lemo Green Park",
    address: "Lemo Green Park, South Africa",
    startsAt: "2026-12-26T14:00:00.000Z",
    endsAt: "2026-12-26T22:00:00.000Z",
    ticketPriceCents: 3500,
    currency: "ZAR",
    capacity: 1400,
    featured: false,
    published: true,
    imageUrl: "/lemofest/upcoming-event-8.png",
    galleryUrls: ["/lemofest/upcoming-event-8.png", "/lemofest/blog9.jpg"],
    tags: ["hangout", "friends", "food"],
    schedule: featuredTimeline,
    displayDateLabel: "26 DECEMBER 2026",
  },
];

export const demoProducts = [
  {
    slug: "lemo-oversized-tee",
    name: "Lemo Oversized Tee",
    description:
      "Heavyweight cotton tee with a boxy fit, washed-black finish, and a bright festival back print.",
    priceCents: 4900,
    compareAtPriceCents: 5900,
    category: "Apparel",
    inventory: 96,
    featured: true,
    active: true,
    imageUrl:
      "https://images.pexels.com/photos/3399996/pexels-photo-3399996.jpeg?auto=compress&cs=tinysrgb&w=1200",
    galleryUrls: [
      "https://images.pexels.com/photos/3399996/pexels-photo-3399996.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
  },
  {
    slug: "midnight-hoodie",
    name: "Midnight Hoodie",
    description:
      "Brushed fleece hoodie with a relaxed silhouette, pouch pocket, and minimal front branding.",
    priceCents: 8900,
    compareAtPriceCents: 10400,
    category: "Outerwear",
    inventory: 58,
    featured: true,
    active: true,
    imageUrl:
      "https://images.pexels.com/photos/28701952/pexels-photo-28701952.jpeg?auto=compress&cs=tinysrgb&w=1200",
    galleryUrls: [
      "https://images.pexels.com/photos/28701952/pexels-photo-28701952.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
  },
  {
    slug: "field-cap",
    name: "Field Cap",
    description:
      "Structured six-panel cap with an embroidered Lemo Fest mark and a curved everyday brim.",
    priceCents: 2600,
    compareAtPriceCents: 3200,
    category: "Headwear",
    inventory: 128,
    featured: false,
    active: true,
    imageUrl:
      "https://images.pexels.com/photos/16117426/pexels-photo-16117426.jpeg?auto=compress&cs=tinysrgb&w=1200",
    galleryUrls: [
      "https://images.pexels.com/photos/16117426/pexels-photo-16117426.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
  },
  {
    slug: "festival-tote",
    name: "Festival Tote",
    description:
      "Canvas tote for event days and everyday carry with a clean screen-printed logo.",
    priceCents: 2900,
    compareAtPriceCents: null,
    category: "Accessories",
    inventory: 140,
    featured: false,
    active: true,
    imageUrl:
      "https://images.pexels.com/photos/35685422/pexels-photo-35685422.jpeg?auto=compress&cs=tinysrgb&w=1200",
    galleryUrls: [
      "https://images.pexels.com/photos/35685422/pexels-photo-35685422.jpeg?auto=compress&cs=tinysrgb&w=1200",
    ],
  },
];

export const demoTestimonials = [
  {
    name: "Mamokete Mosia",
    role: "Festival guest",
    quote: "The flow felt polished from the homepage to checkout.",
    avatarUrl: "/lemofest/testimonial-profile-1.png",
    rating: 5,
    featured: true,
    published: true,
  },
  {
    name: "Keitumetse Itumeleng Josephine Phakoe",
    role: "Repeat attendee",
    quote: "Clean branding, strong visuals, and a platform that feels ready to sell.",
    avatarUrl: "/lemofest/testimonial-profile-2.png",
    rating: 5,
    featured: true,
    published: true,
  },
];

export const demoGallery = [
  {
    slug: "highlights-01",
    title: "Highlight 01",
    description: "Live crowd and stage energy.",
    imageUrl: "/lemofest/blog1.jpg",
    downloadUrl: "/lemofest/blog1.jpg",
    altText: "Lemo Fest highlight image 01",
    featured: true,
    published: true,
  },
  {
    slug: "highlights-02",
    title: "Highlight 02",
    description: "Festival crowd moments.",
    imageUrl: "/lemofest/blog2.jpg",
    downloadUrl: "/lemofest/blog2.jpg",
    altText: "Lemo Fest highlight image 02",
    featured: true,
    published: true,
  },
  {
    slug: "highlights-03",
    title: "Highlight 03",
    description: "Live music and lights.",
    imageUrl: "/lemofest/blog-img-1.png",
    downloadUrl: "/lemofest/blog-img-1.png",
    altText: "Lemo Fest highlight image 03",
    featured: true,
    published: true,
  },
  {
    slug: "highlights-04",
    title: "Highlight 04",
    description: "Night show stills.",
    imageUrl: "/lemofest/latest-blog-news-4.png",
    downloadUrl: "/lemofest/latest-blog-news-4.png",
    altText: "Lemo Fest highlight image 04",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-05",
    title: "Highlight 05",
    description: "Energy on the dance floor.",
    imageUrl: "/lemofest/latest-blog-news-5.png",
    downloadUrl: "/lemofest/latest-blog-news-5.png",
    altText: "Lemo Fest highlight image 05",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-06",
    title: "Highlight 06",
    description: "Late night crowd moments.",
    imageUrl: "/lemofest/blog3.jpg",
    downloadUrl: "/lemofest/blog3.jpg",
    altText: "Lemo Fest highlight image 06",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-07",
    title: "Highlight 07",
    description: "Stage lights and silhouettes.",
    imageUrl: "/lemofest/latest-blog-news-7.png",
    downloadUrl: "/lemofest/latest-blog-news-7.png",
    altText: "Lemo Fest highlight image 07",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-08",
    title: "Highlight 08",
    description: "Fans and festival atmosphere.",
    imageUrl: "/lemofest/blog5.jpg",
    downloadUrl: "/lemofest/blog5.jpg",
    altText: "Lemo Fest highlight image 08",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-09",
    title: "Highlight 09",
    description: "Bright stage coverage.",
    imageUrl: "/lemofest/blog6.jpg",
    downloadUrl: "/lemofest/blog6.jpg",
    altText: "Lemo Fest highlight image 09",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-10",
    title: "Highlight 10",
    description: "Crowd moments and smiles.",
    imageUrl: "/lemofest/blog7.jpg",
    downloadUrl: "/lemofest/blog7.jpg",
    altText: "Lemo Fest highlight image 10",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-11",
    title: "Highlight 11",
    description: "Venue and people in motion.",
    imageUrl: "/lemofest/blog8.jpg",
    downloadUrl: "/lemofest/blog8.jpg",
    altText: "Lemo Fest highlight image 11",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-12",
    title: "Highlight 12",
    description: "Dark stage visual.",
    imageUrl: "/lemofest/blog9.jpg",
    downloadUrl: "/lemofest/blog9.jpg",
    altText: "Lemo Fest highlight image 12",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-13",
    title: "Highlight 13",
    description: "Detail shot from the event.",
    imageUrl: "/lemofest/blog10.jpg",
    downloadUrl: "/lemofest/blog10.jpg",
    altText: "Lemo Fest highlight image 13",
    featured: false,
    published: true,
  },
  {
    slug: "highlights-14",
    title: "Highlight 14",
    description: "Final moments from the show.",
    imageUrl: "/lemofest/blog11.jpg",
    downloadUrl: "/lemofest/blog11.jpg",
    altText: "Lemo Fest highlight image 14",
    featured: false,
    published: true,
  },
];

export const demoSocialPosts = [
  {
    source: "FACEBOOK",
    externalId: "fb-001",
    message:
      "Yanos Hip-Hop tickets are live. Tag the person you are bringing with you to Lemo Green Park.",
    link: "https://facebook.com/lemofest/posts/1",
    imageUrl: "/lemofest/event-img.png",
    authorName: "Lemo Fest",
    publishedAt: "2026-04-01T08:00:00.000Z",
    featured: true,
  },
  {
    source: "FACEBOOK",
    externalId: "fb-002",
    message:
      "The latest highlights reel is live. Re-live the crowd, the lights, and the stage moments from the last event.",
    link: "https://facebook.com/lemofest/posts/2",
    imageUrl: "/lemofest/blog1.jpg",
    authorName: "Lemo Fest",
    publishedAt: "2026-03-29T12:00:00.000Z",
    featured: true,
  },
  {
    source: "FACEBOOK",
    externalId: "fb-003",
    message:
      "Bar card refund instructions are live. Keep your balance or follow the refund steps before the next event.",
    link: "https://facebook.com/lemofest/posts/3",
    imageUrl: "/lemofest/blog2.jpg",
    authorName: "Lemo Fest Ops",
    publishedAt: "2026-03-27T16:30:00.000Z",
    featured: false,
  },
  {
    source: "FACEBOOK",
    externalId: "fb-004",
    message:
      "Fashion, Art & Comedy is coming up next. Secure your pass early and keep an eye on the gallery updates.",
    link: "https://facebook.com/lemofest/posts/4",
    imageUrl: "/lemofest/upcoming-event-7.png",
    authorName: "Lemo Fest",
    publishedAt: "2026-03-26T10:00:00.000Z",
    featured: false,
  },
];

export const demoEnquiries = [
  {
    type: "TICKETS",
    status: "NEW",
    name: "Sarah Mokoena",
    email: "sarah@example.com",
    phone: "+27 82 111 2233",
    subject: "Ticket group booking",
    message:
      "We are looking to book 18 tickets for the Afro Soul & Jazz night and want to know if there is a group rate.",
    source: "WEBSITE",
    notes: null,
    createdAt: "2026-04-01T08:30:00.000Z",
    resolvedAt: null,
  },
  {
    type: "MERCH",
    status: "IN_PROGRESS",
    name: "Lerato Dube",
    email: "lerato@example.com",
    phone: "+27 83 222 3344",
    subject: "Hoodie stock enquiry",
    message:
      "Please confirm when the Midnight Hoodie will be restocked. We need medium and large sizes.",
    source: "WEBSITE",
    notes: "Reply with restock ETA from merch supplier.",
    createdAt: "2026-03-31T13:15:00.000Z",
    resolvedAt: null,
  },
  {
    type: "SPONSORSHIP",
    status: "RESOLVED",
    name: "Nqobile Events",
    email: "events@nqobile.co.za",
    phone: "+27 11 555 9000",
    subject: "Partnership request",
    message:
      "Our brand would like to discuss a sponsorship package for the next Lemo Fest season.",
    source: "EMAIL",
    notes: "Intro call scheduled for Friday.",
    createdAt: "2026-03-28T11:20:00.000Z",
    resolvedAt: "2026-03-29T09:00:00.000Z",
  },
  {
    type: "GENERAL",
    status: "NEW",
    name: "Mpho Letsatsi",
    email: "mpho@example.com",
    phone: null,
    subject: "Event booking question",
    message:
      "Can the team help with a private booking for a birthday event at Lemo Green Park?",
    source: "WEBSITE",
    notes: null,
    createdAt: "2026-03-27T16:45:00.000Z",
    resolvedAt: null,
  },
];

export const demoDiscountCodes = [
  {
    code: "LEMO10",
    description: "10% off tickets and merch for early community members.",
    type: "PERCENTAGE",
    value: 10,
    active: true,
    usageLimit: 250,
  },
];
